namespace FootballLeagueApi.DTOs
{
    /// <summary>
    /// TeamCreateDto - Data Transfer Object for creating a new team
    /// 
    /// DTOs (Data Transfer Objects) are used to define the shape of data
    /// sent to and received from the API. This class represents the data
    /// expected in a POST /api/teams request body.
    /// 
    /// Notice: No TeamId property - the ID is auto-generated by the database
    /// </summary>
    public class TeamCreateDto
    {
        /// <summary>
        /// The name of the team being created (e.g., "Manchester United")
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The name of the team's head coach
        /// </summary>
        public string Coach { get; set; }

        /// <summary>
        /// The year the team was founded
        /// </summary>
        public int FoundedYear { get; set; }
    }
}
