using FootballLeagueApi.Models;

namespace FootballLeagueApi.DTOs
{
    /// <summary>
    /// TeamMapper - Utility class for converting between DTOs and domain models
    /// 
    /// This static class provides methods to convert:
    /// - Domain models (Team) to DTOs (TeamReadDto)
    /// - DTOs (TeamCreateDto) to domain models (Team)
    /// This keeps conversion logic centralized and reusable across the application.
    /// </summary>
    public static class TeamMapper
    {
        /// <summary>
        /// Convert a Team domain model to a TeamReadDto
        /// Used when returning team data to clients in API responses
        /// </summary>
        /// <param name="team">The Team model to convert</param>
        /// <returns>A TeamReadDto with the same data as the Team</returns>
        public static TeamReadDto ToDto(Team team)
        {
            return new TeamReadDto
            {
                TeamId = team.TeamId,
                Name = team.Name,
                Coach = team.Coach,
                FoundedYear = team.FoundedYear,
                Venue = team.Venue
            };
        }

        /// <summary>
        /// Convert a TeamCreateDto to a Team domain model
        /// Used when a client sends POST request data that needs to become a database entity
        /// </summary>
        /// <param name="dto">The TeamCreateDto from the request</param>
        /// <returns>A new Team model ready to be saved to the database</returns>
        public static Team ToModel(TeamCreateDto dto)
        {
            return new Team
            {
                Name = dto.Name,
                Coach = dto.Coach,
                FoundedYear = dto.FoundedYear,
                Venue = dto.Venue
                // Note: TeamId is not set here - it will be auto-generated by the database
            };
        }
    }
}
