using FootballLeagueApi.DTOs;
using FootballLeagueApi.Models;
using FootballLeagueApi.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FootballLeagueApi.Controllers
{
    /// <summary>
    /// Teams Controller - Manages REST API operations for football teams
    /// 
    /// This controller provides endpoints for creating, reading, updating, and deleting team records.
    /// Teams represent the individual clubs participating in the football league.
    /// All operations are logged and include comprehensive error handling.
    /// 
    /// Base route: /api/teams
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public class TeamsController : ControllerBase
    {
        private readonly ITeamService _teamService;
        private readonly ILogger<TeamsController> _logger;

        /// <summary>
        /// Constructor for dependency injection of TeamService and Logger
        /// </summary>
        /// <param name="teamService">Service for team business logic operations</param>
        /// <param name="logger">Logger for tracking operations and errors</param>
        public TeamsController(ITeamService teamService, ILogger<TeamsController> logger)
        {
            _teamService = teamService;
            _logger = logger;
        }

        /// <summary>
        /// Retrieve all teams in the league
        /// 
        /// Returns a complete list of all registered teams with their details.
        /// This endpoint is useful for populating dropdowns, lists, or team selection interfaces.
        /// </summary>
        /// <returns>
        /// 200 OK - Returns an array of TeamReadDto objects containing all teams
        /// Example: [{ "teamId": 1, "name": "Manchester United", "coach": "Erik ten Hag", "foundedYear": 1878 }]
        /// </returns>
        /// <response code="200">List of all teams successfully retrieved</response>
        /// <response code="500">Internal server error occurred while fetching teams</response>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<TeamReadDto>), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> GetAll()
        {
            try
            {
                _logger.LogInformation("Fetching all teams");
                var teams = await _teamService.GetAllAsync();
                _logger.LogInformation("Successfully retrieved {Count} teams", teams.Count());
                var dto = teams.Select(t => TeamMapper.ToDto(t));
                return Ok(dto);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching all teams");
                throw;
            }
        }

        /// <summary>
        /// Retrieve a specific team by its ID
        /// 
        /// Fetches detailed information about a single team including name, coach, and founding year.
        /// This endpoint is used when you need information about a particular team.
        /// </summary>
        /// <param name="id">The unique identifier of the team (primary key)</param>
        /// <returns>
        /// 200 OK - Returns TeamReadDto with team details
        /// Example: { "teamId": 1, "name": "Manchester United", "coach": "Erik ten Hag", "foundedYear": 1878 }
        /// </returns>
        /// <response code="200">Team found and returned successfully</response>
        /// <response code="404">Team with specified ID not found</response>
        /// <response code="500">Internal server error occurred</response>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(TeamReadDto), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> GetById(int id)
        {
            try
            {
                _logger.LogInformation("Fetching team with ID {TeamId}", id);
                var team = await _teamService.GetByIdAsync(id);
                if (team == null)
                {
                    _logger.LogWarning("Team with ID {TeamId} not found", id);
                    return NotFound();
                }
                _logger.LogInformation("Successfully retrieved team with ID {TeamId}", id);
                return Ok(TeamMapper.ToDto(team));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching team with ID {TeamId}", id);
                throw;
            }
        }

        /// <summary>
        /// Create a new team in the league
        /// 
        /// Adds a new team to the system. The team ID is auto-generated by the database.
        /// Requires team name, coach name, and founding year.
        /// Returns the created team with its assigned ID.
        /// </summary>
        /// <param name="dto">TeamCreateDto containing team name, coach, and founded year</param>
        /// <returns>
        /// 201 Created - Returns TeamReadDto with the newly created team and its assigned ID
        /// Example: { "teamId": 1, "name": "Manchester United", "coach": "Erik ten Hag", "foundedYear": 1878 }
        /// Location header points to GET /api/teams/1
        /// </returns>
        /// <response code="201">Team successfully created</response>
        /// <response code="400">Invalid team data provided</response>
        /// <response code="500">Internal server error occurred</response>
        [HttpPost]
        [Authorize]
        [ProducesResponseType(typeof(TeamReadDto), StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> Create(TeamCreateDto dto)
        {
            try
            {
                _logger.LogInformation("Creating new team: {TeamName}", dto.Name);
                var team = TeamMapper.ToModel(dto);
                var created = await _teamService.CreateAsync(team);
                _logger.LogInformation("Successfully created team with ID {TeamId}", created.TeamId);
                return CreatedAtAction(nameof(GetById), new { id = created.TeamId }, TeamMapper.ToDto(created));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating team: {TeamName}", dto.Name);
                throw;
            }
        }

        /// <summary>
        /// Update an existing team's information
        /// 
        /// Modifies team details such as name, coaching staff, or founding year.
        /// Requires the team ID in the URL path. The team ID cannot be changed.
        /// Returns 204 No Content on success, 404 if team not found.
        /// </summary>
        /// <param name="id">The ID of the team to update</param>
        /// <param name="dto">TeamUpdateDto containing updated team information</param>
        /// <returns>
        /// 204 No Content - Team successfully updated (no response body)
        /// </returns>
        /// <response code="204">Team updated successfully</response>
        /// <response code="404">Team with specified ID not found</response>
        /// <response code="400">Invalid team data or update operation failed</response>
        /// <response code="500">Internal server error occurred</response>
        [HttpPut("{id}")]
        [Authorize]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> Update(int id, TeamUpdateDto dto)
        {
            try
            {
                _logger.LogInformation("Updating team with ID {TeamId}: {TeamName}", id, dto.Name);
                var team = new Team
                {
                    TeamId = id,
                    Name = dto.Name,
                    Coach = dto.Coach,
                    FoundedYear = dto.FoundedYear,
                    Venue = dto.Venue
                };

                var success = await _teamService.UpdateAsync(id, team);
                if (!success)
                {
                    _logger.LogWarning("Team with ID {TeamId} not found for update", id);
                    return NotFound();
                }

                _logger.LogInformation("Successfully updated team with ID {TeamId}", id);
                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating team with ID {TeamId}", id);
                throw;
            }
        }

        /// <summary>
        /// Delete a team from the league
        /// 
        /// Permanently removes a team from the system. This operation is irreversible.
        /// Returns 204 No Content on success, 404 if team not found.
        /// Note: Deleting a team may affect related match records depending on database constraints.
        /// </summary>
        /// <param name="id">The ID of the team to delete</param>
        /// <returns>
        /// 204 No Content - Team successfully deleted (no response body)
        /// </returns>
        /// <response code="204">Team deleted successfully</response>
        /// <response code="404">Team with specified ID not found</response>
        /// <response code="409">Team cannot be deleted because it has dependent records</response>
        /// <response code="500">Internal server error occurred</response>
        [HttpDelete("{id}")]
        [Authorize(Roles = "Admin")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                _logger.LogInformation("Deleting team with ID {TeamId}", id);
                var success = await _teamService.DeleteAsync(id);
                if (!success)
                {
                    _logger.LogWarning("Team with ID {TeamId} not found for deletion", id);
                    return NotFound();
                }

                _logger.LogInformation("Successfully deleted team with ID {TeamId}", id);
                return NoContent();
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Delete blocked for team with ID {TeamId}", id);
                return Conflict(new { error = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting team with ID {TeamId}", id);
                throw;
            }
        }
    }
}
