using System.Text.Json.Serialization;

namespace FootballLeagueApi.Models
{
    /// <summary>
    /// MatchEvent Model - Represents an event that occurs during a match
    /// 
    /// Examples of match events include: goals scored, yellow/red cards, substitutions, own goals, etc.
    /// Each event is linked to a specific match and occurs at a specific minute.
    /// A player is optionally associated (e.g., yellow cards might not have a player in the model).
    /// </summary>
    public class MatchEvent
    {
        /// <summary>
        /// Unique identifier for the match event (Primary Key)
        /// Auto-generated by the database
        /// </summary>
        public int MatchEventId { get; set; }

        /// <summary>
        /// Foreign key: ID of the match this event occurred in
        /// Links to the Match table
        /// </summary>
        public int MatchId { get; set; }

        /// <summary>
        /// Foreign key: ID of the player involved in this event (optional)
        /// Nullable because some events (e.g., fan incidents) may not involve a specific player
        /// Links to the Player table
        /// </summary>
        public int? PlayerId { get; set; }

        /// <summary>
        /// The minute (game time) when the event occurred
        /// For example, a goal in the 45th minute would have Minute = 45
        /// </summary>
        public int Minute { get; set; }

        /// <summary>
        /// The type of event that occurred
        /// Examples: "Goal", "YellowCard", "RedCard", "Substitution", "OwnGoal", etc.
        /// This is a string to allow flexibility in event types without enum constraints
        /// </summary>
        public string EventType { get; set; }

        /// <summary>
        /// Navigation property: Reference to the Match this event belongs to
        /// [JsonIgnore] prevents the entire match object from being serialized
        /// in API responses to keep responses lightweight
        /// </summary>
        [JsonIgnore]
        public Match? Match { get; set; }

        /// <summary>
        /// Navigation property: Reference to the Player involved in this event (if applicable)
        /// [JsonIgnore] prevents the entire player object from being serialized
        /// Will be null if the event doesn't involve a specific player
        /// </summary>
        [JsonIgnore]
        public Player? Player { get; set; }
    }
}
