using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FootballLeagueApi.Models
{
    /// <summary>
    /// Match Model - Represents a football match between two teams
    /// 
    /// A match is a game between a home team and an away team at a specific venue.
    /// It belongs to a season and can have multiple match events (goals, cards, substitutions).
    /// The match tracks both teams, location, timing, and final score.
    /// </summary>
    public class Match
    {
        /// <summary>
        /// Unique identifier for the match (Primary Key)
        /// Auto-generated by the database
        /// </summary>
        public int MatchId { get; set; }

        /// <summary>
        /// Foreign key: ID of the team playing at home
        /// Links to the Team table
        /// </summary>
        public int HomeTeamId { get; set; }

        /// <summary>
        /// Foreign key: ID of the team playing away
        /// Links to the Team table
        /// </summary>
        public int AwayTeamId { get; set; }

        /// <summary>
        /// Foreign key: ID of the season this match belongs to
        /// Every match must be part of a specific season
        /// Links to the Season table
        /// </summary>
        public int SeasonId { get; set; }

        /// <summary>
        /// The date and time when the match kicks off
        /// Determines when the match is scheduled to start
        /// </summary>
        public DateTime KickoffTime { get; set; }

        /// <summary>
        /// The final score for the home team
        /// Updated after the match is completed
        /// </summary>
        public int HomeScore { get; set; }

        /// <summary>
        /// The final score for the away team
        /// Updated after the match is completed
        /// </summary>
        public int AwayScore { get; set; }

        /// <summary>
        /// Navigation property: Reference to the home Team object
        /// [JsonIgnore] prevents the entire team object from being serialized
        /// in API responses to keep responses lightweight
        /// </summary>
        [JsonIgnore]
        public Team? HomeTeam { get; set; }

        /// <summary>
        /// Navigation property: Reference to the away Team object
        /// [JsonIgnore] prevents the entire team object from being serialized
        /// </summary>
        [JsonIgnore]
        public Team? AwayTeam { get; set; }

        /// <summary>
        /// Navigation property: Reference to the Season this match belongs to
        /// [JsonIgnore] prevents the season object from being serialized
        /// </summary>
        [JsonIgnore]
        public Season? Season { get; set; }

        /// <summary>
        /// Navigation property: Collection of all events that occurred during this match
        /// Includes goals, yellow/red cards, substitutions, etc.
        /// Related through the MatchEvent.MatchId foreign key
        /// [JsonIgnore] prevents nested event data in responses
        /// </summary>
        [JsonIgnore]
        public List<MatchEvent>? MatchEvents { get; set; }
    }
}
