using System.Text.Json.Serialization;

namespace FootballLeagueApi.Models
{
    /// <summary>
    /// Player Model - Represents a football player in the league
    /// 
    /// This model stores information about individual players and their team assignment.
    /// The Team navigation property is marked with [JsonIgnore] to prevent circular references
    /// when serializing to JSON (avoiding infinitely nested data).
    /// </summary>
    public class Player
    {
        /// <summary>
        /// Unique identifier for the player (Primary Key)
        /// Auto-generated by the database
        /// </summary>
        public int PlayerId { get; set; }

        /// <summary>
        /// The full name of the player
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// The shirt number worn by the player (typically 1-99)
        /// </summary>
        public int ShirtNumber { get; set; }

        /// <summary>
        /// The player's position on the field (e.g., "Goalkeeper", "Defender", "Midfielder", "Forward")
        /// Nullable because some players may not have a position defined
        /// </summary>
        public string? Position { get; set; }

        /// <summary>
        /// Foreign key reference to the team this player plays for
        /// Links this player to a Team record in the database
        /// </summary>
        public int TeamId { get; set; }

        /// <summary>
        /// Navigation property: Reference to the Team this player belongs to
        /// [JsonIgnore] prevents the full team object from being serialized in API responses
        /// This avoids circular reference issues (Player -> Team -> Players -> Player...)
        /// </summary>
        [JsonIgnore]
        public Team? Team { get; set; }
    }
}
