using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FootballLeagueApi.Models
{
    /// <summary>
    /// Season Model - Represents a football league season
    /// 
    /// A season is a time period (typically one year) in which all matches are played.
    /// For example, the 2025/26 season runs from a specified start date to an end date.
    /// All matches in the league must belong to a season.
    /// </summary>
    public class Season
    {
        /// <summary>
        /// Unique identifier for the season (Primary Key)
        /// Auto-generated by the database
        /// </summary>
        public int SeasonId { get; set; }

        /// <summary>
        /// The name/identifier for the season (e.g., "2025/26", "Premier League 2025-26")
        /// Typically formatted as start year slash end year
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The date when this season starts (e.g., August 1, 2025)
        /// Matches cannot be scheduled before this date
        /// </summary>
        public DateTime StartDate { get; set; }

        /// <summary>
        /// The date when this season ends (e.g., May 31, 2026)
        /// Matches cannot be scheduled after this date
        /// </summary>
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Navigation property: Collection of all matches that belong to this season
        /// Related through the Match.SeasonId foreign key
        /// [JsonIgnore] prevents the full list of matches from being serialized
        /// to avoid overly large API responses with nested match data
        /// </summary>
        [JsonIgnore]
        public List<Match>? Matches { get; set; }
    }
}
