namespace FootballLeagueApi.Models
{
    /// <summary>
    /// Team Model - Represents a football team in the league
    /// 
    /// This is a domain model that maps to the Teams database table.
    /// It contains the team's basic information and navigation properties
    /// for relationships (players who play for the team, matches they play in)
    /// </summary>
    public class Team
    {
        /// <summary>
        /// Unique identifier for the team (Primary Key)
        /// Auto-generated by the database
        /// </summary>
        public int TeamId { get; set; }

        /// <summary>
        /// The name of the team (e.g., "Arsenal")
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The name of the team's head coach
        /// </summary>
        public string Coach { get; set; }

        /// <summary>
        /// The year the team was founded
        /// </summary>
        public int FoundedYear { get; set; }

        /// <summary>
        /// Navigation property: Collection of matches where this team played at home
        /// Related through the Match.HomeTeamId foreign key
        /// </summary>
        public ICollection<Match> HomeMatches { get; set; }

        /// <summary>
        /// Navigation property: Collection of matches where this team played away
        /// Related through the Match.AwayTeamId foreign key
        /// </summary>
        public ICollection<Match> AwayMatches { get; set; }

        /// <summary>
        /// Navigation property: Collection of players that currently play for this team
        /// Related through the Player.TeamId foreign key
        /// </summary>
        public ICollection<Player> Players { get; set; }
    }
}
