using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FootballLeagueApi.Models
{
    /// <summary>
    /// Venue Model - Represents a football stadium or venue
    /// 
    /// A venue is a physical location (stadium, ground) where matches are played.
    /// Multiple matches can be played at the same venue throughout a season.
    /// </summary>
    public class Venue
    {
        /// <summary>
        /// Unique identifier for the venue (Primary Key)
        /// Auto-generated by the database
        /// </summary>
        public int VenueId { get; set; }

        /// <summary>
        /// The name of the venue/stadium (e.g., "Old Trafford", "Anfield")
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The physical address of the venue (street, city, postcode)
        /// Nullable because some venues may not have a recorded address
        /// </summary>
        public string? Address { get; set; }

        /// <summary>
        /// Navigation property: Collection of all matches played at this venue
        /// Related through the Match.VenueId foreign key
        /// [JsonIgnore] prevents the full list of matches from being serialized
        /// to avoid overly large API responses
        /// </summary>
        [JsonIgnore]
        public List<Match>? Matches { get; set; }
    }
}
